version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Print node version
          command: node --version
      - run:
          name: Install dev dependencies
          command: npm install --save-dev
      - run:
          name: Feature tests
          command: npm run feature-test
      - run:
          name: Unit tests
          command: npm run unit-test
      - run:
          name: Type checks
          command: npm run flow
      - run:
          name: Linter
          command: npm run lint
