version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: 12.18.0
      - run:
          name: Install dev dependencies
          command: npm install --save-dev
      - run:
          name: Feature tests
          command: npm run feature-test
      - run:
          name: Unit tests
          command: npm run unit-test
      - run:
          name: Type checks
          command: npm run flow
      - run:
          name: Linter
          command: npm run lint
workflows:
    build-and-test:
      jobs:
        - build-and-test